---

- name: set nodes on exports file
  lineinfile:
    dest: /etc/exports
    line: "{{ item.line }}"
  become: yes
  with_items:
    - { line: '/srv/nfs {{master_ip}}(rw,sync)'}
    - { line: '/srv/nfs {{worker_ip}}(rw,sync)'}