---

- name: exposing firewall ports
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    inmediate: yes
  become: true
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded