---

- name: exposing firewall ports
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  become: true
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: reload service firewalld
  service:
    name: firewalld
    state: restarted
  become: true
