---

- name: activate transparent masquerading
  modprobe:
    name: br_netfilter
    state: present
  become: yes

- name: exposing firewall ports
  firewalld:
    permanent: yes
    masquerade: yes
    state: enabled
  become: true

- name: reload service firewalld
  service:
    name: firewalld
    state: restarted
  become: true

- name: check/create file k8s.config
  copy:
    content: "{{ item }}"
    dest: /etc/sysctl.d/k8s.conf
    force: no
    group: sys
    owner: root
  become: true
  with_items:
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.bridge.bridge-nf-call-iptables = 1

- name: reload sysctl
  command: sysctl --system
  become: true

- name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
    become: true

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes

- name: Install Docker
  dnf:
    name:
     - docker-ce-19.03.14-3.el8
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
  become: yes
  
  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl
    become: yes

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
  become: yes