---

- name: install Tigera
  command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
  become: true

- name: install definition file for Calico
  command: wget https://docs.projectcalico.org/manifests/custom-resources.yaml
  become: true
