---

- name: open firewall ports
  firewalld:
    permanent: yes
    zone: public
    state: enabled
    port: "{{ item }}"
  become: true
  with_items:
    - 10250/tcp
    - 30000-32767/tcp
  when: inventory_hostname in groups['workers']

- name: reload service firewalld
  service:
    name: firewalld
    state: restarted
  become: true
  when: inventory_hostname in groups['workers']

# Si se trata la salida almacenada en join command para obtener las líneas del comando
# en lugar de la salida entera, se puede ejecutar directamente en esta task.
#- name: Join workers to cluster
#  command: ./join-command
#  become: true
#  when: inventory_hostname in groups['workers']