---

#- name: open firewall ports
#  firewalld:
#    permanent: yes
#    zone: public
#    state: enabled
#    port: "{{ item }}"
#  become: true
#  with_items:
#    - 10250/tcp
#    - 30000-32767/tcp
#  when: inventory_hostname in groups['workers']
#
#- name: reload service firewalld
#  service:
#    name: firewalld
#    state: restarted
#  become: true
#  when: inventory_hostname in groups['workers']


- name: reset kubeadm
  expect:
    command: kubeadm reset
    responses: 
      '[y/N]': "y"
  become: true
  when: inventory_hostname in groups['master']

- name: defining POD network
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  become: true
  register: init_output
  when: inventory_hostname in groups['master']

- name: Copy join command to local file
  local_action:
    module: copy
    content: |
      {{ init_output.stdout[-2] }}
      {{ init_output.stdout[-1] }}
    dest: "./join-command"

- name: Join workers to cluster
  command: ./join-command
  become: true
  when: inventory_hostname in groups['workers']