---

- name: open firewall ports
  firewalld:
    permanent: yes
    zone: public
    state: enabled
    port: "{{ item }}"
  become: true
  with_items:
    - "{10250,30000-32767}/tcp"
  when: inventory_hostname in groups['workers']

- name: reload service firewalld
  service:
    name: firewalld
    state: restarted
  become: true
  when: inventory_hostname in groups['workers']

- name: Join workers to cluster
  command: "{{ kubeadm_pod_network }}"
  become: true
  when: inventory_hostname in groups['workers']