---

- name: setting initial configuration
  hosts: all
  tasks:
    - name: set time zone to Europe/Madrid
      timezone:
        name: Europe/Madrid
      become: yes
      become_method: sudo
    - name: install chrony
      dnf:
        name: chrony
        state: latest
      become: yes
      become_method: sudo
    - name: enable chrony
      service:
        name: chronyd
        enabled: yes
      become: yes
      become_method: sudo
    - name: start chronyd
      service:
        name: chronyd
        state: started
      become: yes
      become_method: sudo
    - name: run Timedatectl
        command: timedatectl set-ntp true
      become: yes
      become_method: sudo
    - name: Disable SELinux
      selinux:
        state: disabled
      become: yes
      become_method: sudo
    - name: install nfs utils
      dnf:
        name: 
          - nfs-utils
          - nfs4-acl-tools
          - wget
        state: latest
      become: yes
      become_method: sudo

