---

- name: setting initial configuration
  hosts: all
  tasks:
    - name: set time zone to Europe/Madrid
      timezone:
        name: Europe/Madrid
      become: yes
      become_method: sudo
    - name: install chrony
      dnf:
        name: chrony
        state: latest
    - name: enable chrony
      service:
        name: chronyd
        enabled: yes
    - name: start chronyd
      service:
        name: chronyd
        state: started
    - name: Make sure ntp is started and enabled on restart
      service:
        name: ntp
        state: started
        enabled: yes
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: install chrony
      dnf:
        name: 
          - nfs-utils
          - nfs4-acl-tools
          - wget
        state: latest
